// LAUNCHING A CUSTOM WEB APPLICATION ONTO THE CLIENT'S OWN ACCOUNTS.
//
// A build is not live until it is hosted outside our sandbox. This takes a finished custom app there,
// one confirmed step at a time, each with something to show for it:
//   code      a private repository on the client's GitHub, holding the app. Built and tried for real.
//   hosting   a Railway project running that repository, with an address. Built, but switched off
//             (LAUNCH_HOSTING=on) until it has been tried with a real Railway account key, because it
//             creates things in somebody else's account and must not be first run on a customer.
//   check     opening the live address and confirming it serves the app.
//
// Keys are never seen here: Keys.withKey lends one to a single step and logs the use.

const { query } = require('../../config/db');
const P = require('../../lib/permissions');
const Keys = require('./keys');

const GH = 'https://api.github.com';

function slug(s, max) {
  return String(s || '').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, max || 60).replace(/-+$/g, '');
}

function suggestName(businessName, askedFor) {
  const words = String(askedFor || '').split(/\s+/).filter((w) => w.length > 3).slice(0, 3).join(' ');
  return slug((businessName || 'business') + ' ' + (words || 'app'), 60) || 'business-app';
}

// What goes into the repository. A plain Node server with no dependencies, so it runs anywhere.
function packageFiles({ html, businessName, askedFor, repoName }) {
  const server = [
    "// Serves the app. Generated by Penny in Access YP Labs; yours to change.",
    "const http = require('http');",
    "const fs = require('fs');",
    "const path = require('path');",
    "",
    "const page = fs.readFileSync(path.join(__dirname, 'index.html'));",
    "const port = process.env.PORT || 3000;",
    "",
    "http.createServer((req, res) => {",
    "  if (req.method === 'GET' && (req.url === '/' || req.url.startsWith('/?'))) {",
    "    res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8', 'X-Content-Type-Options': 'nosniff' });",
    "    return res.end(page);",
    "  }",
    "  if (req.method === 'GET' && req.url === '/health') {",
    "    res.writeHead(200, { 'Content-Type': 'application/json' });",
    "    return res.end('{\"ok\":true}');",
    "  }",
    "  res.writeHead(404, { 'Content-Type': 'text/plain; charset=utf-8' });",
    "  res.end('Not found');",
    "}).listen(port, () => console.log('Listening on ' + port));",
    "",
  ].join('\n');
  const pkg = JSON.stringify({
    name: slug(repoName, 60) || 'business-app', version: '1.0.0', private: true,
    description: 'Built by Penny in Access YP Labs for ' + businessName,
    scripts: { start: 'node server.js' }, engines: { node: '>=18' },
  }, null, 2) + '\n';
  const readme = [
    '# ' + businessName,
    '',
    'This app was built by Penny in Access YP Labs, from this request:',
    '',
    '> ' + String(askedFor || '').replace(/\n/g, ' '),
    '',
    '## Running it',
    '',
    'Node 18 or newer. Run `npm start` and open http://localhost:3000. It has no dependencies.',
    '',
    '## What is not done yet',
    '',
    'Forms on the page show a message instead of sending anything. Where their information should go is a',
    'decision for you, and it usually needs a database and keys to other services. Ask Penny to add it.',
    '',
    'This code is yours. Change it, move it, or host it anywhere that runs Node.',
    '',
  ].join('\n');
  return [
    { path: 'index.html', content: html },
    { path: 'server.js', content: server },
    { path: 'package.json', content: pkg },
    { path: 'README.md', content: readme },
    { path: '.gitignore', content: 'node_modules/\n.env\n' },
  ];
}

async function gh(token, method, url, body) {
  const r = await fetch(GH + url, {
    method, signal: AbortSignal.timeout(20000),
    headers: { Authorization: 'Bearer ' + token, Accept: 'application/vnd.github+json',
      'User-Agent': 'access-yp-labs', 'Content-Type': 'application/json' },
    body: body ? JSON.stringify(body) : undefined,
  });
  let data = null;
  try { data = await r.json(); } catch (_) { data = null; }
  return { status: r.status, ok: r.ok, data };
}

// ------------------------------------------------------------------ gates

async function gate(viewer, build_id) {
  const b = (await query(
    `SELECT b.*, bz.name AS business_name, p.html FROM builds b
       JOIN businesses bz ON bz.id=b.business_id
       LEFT JOIN build_pages p ON p.build_id=b.id WHERE b.id=$1`, [build_id])).rows[0];
  if (!b) return { ok: false, kind: 'unavailable', says: 'I cannot find that build.' };
  const pj = await P.can(viewer.id, b.business_id, 'projects', 'act');
  if (!pj.ok) return { ok: false, kind: 'refused', says: P.refusalLine(pj, 'projects', pj.perms && pj.perms.business.name) };
  const ky = await P.can(viewer.id, b.business_id, 'keys', 'act');
  if (!ky.ok) return { ok: false, kind: 'refused', says: P.refusalLine(ky, 'keys', ky.perms && ky.perms.business.name) };
  if (b.tier !== 'custom_app') {
    return { ok: false, kind: 'refused', says: b.tier === 'labs_site'
      ? 'This is a site hosted here, so it goes online with Put it online rather than a launch.'
      : 'Only a custom web application is launched onto your own accounts.' };
  }
  if (b.stage !== 'real' || b.status !== 'ready' || !b.html) {
    return { ok: false, kind: 'refused', says: 'That one is not a finished build yet, so there is nothing to launch.' };
  }
  return { ok: true, build: b };
}

async function latest(build_id) {
  const l = (await query('SELECT * FROM launches WHERE build_id=$1 ORDER BY created_at DESC LIMIT 1', [build_id])).rows[0];
  if (!l) return null;
  const steps = (await query('SELECT step, status, says, result, created_at, finished_at FROM launch_steps WHERE launch_id=$1 ORDER BY created_at', [l.id])).rows;
  return Object.assign(l, { steps });
}

function hostingOn() { return process.env.LAUNCH_HOSTING === 'on'; }

async function status(viewer, build_id) {
  const g = await gate(viewer, build_id);
  if (!g.ok) return g;
  const keys = await Keys.list(viewer, g.build.business_id);
  const have = keys.ok ? keys.keys.map((k) => k.service) : [];
  const railwayKind = keys.ok ? ((keys.keys.find((k) => k.service === 'railway') || {}).checked || {}).kind : null;
  const l = await latest(build_id);
  const done = (step) => !!(l && l.steps.some((s) => s.step === step && s.status === 'done'));
  const next = [];
  if (!done('code')) next.push(have.includes('github') ? 'Put the code on your GitHub.' : 'Add a GitHub key on the Keys page.');
  else if (!done('hosting')) {
    if (!hostingOn()) next.push('Hosting on Railway is not switched on yet, so the app is on GitHub but not live.');
    else if (!have.includes('railway')) next.push('Add a Railway account or workspace key on the Keys page.');
    else if (railwayKind === 'project') next.push('The Railway key on file is a project key, which cannot create a project. Add an account or workspace key.');
    else next.push('Start it on Railway.');
  } else if (!done('check')) next.push('Check the live address.');
  const live = done('check');
  return { ok: true, launch: l, keys: have, hosting_available: hostingOn(),
    suggested_repo_name: suggestName(g.build.business_name, g.build.asked_for),
    says: (live ? 'It is live at ' + l.live_url + '.' : 'It is not live yet: it only runs in the preview until it is hosted on your own accounts.')
      + (next.length ? ' Next: ' + next.join(' ') : '') };
}

async function stepRow(launch_id, step, viewer, fn) {
  const row = (await query(
    `INSERT INTO launch_steps (launch_id, step, status, says, confirmed_by) VALUES ($1,$2,'running','Started.',$3) RETURNING id`,
    [launch_id, step, viewer.id])).rows[0];
  let out;
  try { out = await fn(); } catch (e) { out = { ok: false, says: 'It stopped partway: ' + e.message }; }
  await query(
    `UPDATE launch_steps SET status=$2, says=$3, result=$4, finished_at=now() WHERE id=$1`,
    [row.id, out.ok ? 'done' : 'failed', out.says, out.ok ? String(out.result) : null]);
  await query('UPDATE launches SET updated_at=now() WHERE id=$1', [launch_id]);
  return out;
}

// ------------------------------------------------------------------ step 1: code

async function pushCode(viewer, build_id, { repo_name }) {
  const g = await gate(viewer, build_id);
  if (!g.ok) return g;
  const b = g.build;
  const name = slug(repo_name || suggestName(b.business_name, b.asked_for), 100);
  if (!name) return { ok: false, kind: 'unclear', says: 'Choose a repository name of letters, numbers and dashes.' };
  const prior = await latest(build_id);
  if (prior && prior.steps.some((s) => s.step === 'code' && s.status === 'done')) {
    return { ok: false, kind: 'refused', says: 'The code is already on GitHub at ' + prior.repo_url + '.' };
  }
  const l = prior || (await query(
    `INSERT INTO launches (build_id, business_id, started_by, repo_name) VALUES ($1,$2,$3,$4) RETURNING *`,
    [b.id, b.business_id, viewer.id, name])).rows[0];
  if (prior) await query('UPDATE launches SET repo_name=$2 WHERE id=$1', [l.id, name]);

  const out = await stepRow(l.id, 'code', viewer, () => Keys.withKey(b.business_id, 'github',
    { action: 'create repository ' + name + ' and push the app', actor_id: viewer.id, via: 'person' },
    async (token) => {
      const me = await gh(token, 'GET', '/user');
      if (!me.ok) return { ok: false, says: 'GitHub did not accept the key on file. Replace it on the Keys page.' };
      const made = await gh(token, 'POST', '/user/repos', {
        name, private: true, auto_init: false, description: 'Built by Penny in Access YP Labs for ' + b.business_name,
      });
      if (made.status === 422) {
        return { ok: false, says: 'There is already a repository called ' + name + ' on ' + me.data.login
          + '\u2019s GitHub, and I will not write over it. Choose another name.' };
      }
      if (!made.ok) {
        return { ok: false, says: 'GitHub would not create the repository'
          + (made.status === 403 ? ', because the key does not allow creating repositories. A fine-grained key needs Administration set to read and write for new repositories.' : ' (' + made.status + ').') };
      }
      const full = made.data.full_name;
      const files = packageFiles({ html: b.html, businessName: b.business_name, askedFor: b.asked_for, repoName: name });
      for (const f of files) {
        const put = await gh(token, 'PUT', '/repos/' + full + '/contents/' + f.path, {
          message: 'Add ' + f.path + ', built by Penny',
          content: Buffer.from(f.content, 'utf8').toString('base64'),
        });
        if (!put.ok) {
          return { ok: false, says: 'The repository ' + full + ' was created, but GitHub refused ' + f.path
            + ' (' + put.status + '), so the code is incomplete there. Nothing else was changed.' };
        }
      }
      // Read it back rather than trusting the writes.
      const tree = await gh(token, 'GET', '/repos/' + full + '/contents/');
      const names = (tree.data || []).map((x) => x.name);
      const missing = files.map((f) => f.path).filter((p) => !names.includes(p));
      if (missing.length) return { ok: false, says: 'GitHub does not show ' + missing.join(', ') + ' in ' + full + ', so I am not calling this done.' };
      return { ok: true, result: made.data.html_url,
        says: 'The app is on your GitHub at ' + made.data.html_url + ', private, with ' + files.length
          + ' files. The code is yours. It is not live yet: it still needs hosting.' };
    }));
  if (out.ok) {
    await query('UPDATE launches SET repo_url=$2 WHERE id=$1', [l.id, out.result]);
    await query('UPDATE builds SET repo_url=$2, handed_over_at=now(), updated_at=now() WHERE id=$1', [b.id, out.result]);
  }
  return out.ok ? { ok: true, says: out.says, repo_url: out.result }
    : { ok: false, kind: out.missing ? 'refused' : 'unavailable', says: out.says };
}

// ------------------------------------------------------------------ step 2: hosting (switched off)

async function railway(token, kind, q, variables) {
  const headers = { 'Content-Type': 'application/json' };
  if (kind === 'project') headers['Project-Access-Token'] = token; else headers.Authorization = 'Bearer ' + token;
  const r = await fetch('https://backboard.railway.com/graphql/v2', {
    method: 'POST', headers, signal: AbortSignal.timeout(30000),
    body: JSON.stringify({ query: q, variables: variables || {} }),
  });
  const d = await r.json().catch(() => ({}));
  if (d.errors && d.errors.length) throw new Error(d.errors.map((e) => e.message).join('; '));
  if (!r.ok) throw new Error('Railway answered ' + r.status);
  return d.data;
}

async function host(viewer, build_id) {
  const g = await gate(viewer, build_id);
  if (!g.ok) return g;
  if (!hostingOn()) {
    return { ok: false, kind: 'refused', says: 'Hosting on Railway is built but has not yet been tried with a real '
      + 'Railway account key, so it is switched off. Your code is on GitHub and nothing else was changed.' };
  }
  const l = await latest(build_id);
  if (!l || !l.steps.some((s) => s.step === 'code' && s.status === 'done')) {
    return { ok: false, kind: 'refused', says: 'Put the code on GitHub first.' };
  }
  const b = g.build;
  const repo = String(l.repo_url || '').replace(/^https:\/\/github\.com\//, '');
  const out = await stepRow(l.id, 'hosting', viewer, () => Keys.withKey(b.business_id, 'railway',
    { action: 'create a Railway project for ' + repo, actor_id: viewer.id, via: 'person' },
    async (token, meta) => {
      if (meta.checked.kind === 'project') {
        return { ok: false, says: 'The Railway key on file is a project key, which cannot create a project. Add an account or workspace key.' };
      }
      const p = await railway(token, meta.checked.kind, 'mutation($i: ProjectCreateInput!) { projectCreate(input: $i) { id environments { edges { node { id name } } } } }',
        { i: { name: l.repo_name } });
      const projectId = p.projectCreate.id;
      const env = (p.projectCreate.environments.edges[0] || {}).node;
      if (!env) return { ok: false, says: 'Railway created project ' + projectId + ' but gave it no environment, so I stopped.' };
      let s;
      try {
        s = await railway(token, meta.checked.kind, 'mutation($i: ServiceCreateInput!) { serviceCreate(input: $i) { id } }',
          { i: { projectId, name: l.repo_name, source: { repo } } });
      } catch (e) {
        return { ok: false, says: 'Railway created a project but could not read the repository ' + repo
          + '. Railway needs its GitHub app installed on your GitHub with access to that repository. ' + e.message };
      }
      const serviceId = s.serviceCreate.id;
      const d = await railway(token, meta.checked.kind, 'mutation($i: ServiceDomainCreateInput!) { serviceDomainCreate(input: $i) { domain } }',
        { i: { serviceId, environmentId: env.id } });
      const url = 'https://' + d.serviceDomainCreate.domain;
      await query('UPDATE launches SET railway_project_id=$2, railway_service_id=$3, live_url=$4 WHERE id=$1',
        [l.id, projectId, serviceId, url]);
      return { ok: true, result: url, says: 'Railway is building it now at ' + url + '. That usually takes a few minutes. '
        + 'Then choose Check the live address, and I will open it to confirm.' };
    }));
  return out.ok ? { ok: true, says: out.says, live_url: out.result } : { ok: false, kind: 'unavailable', says: out.says };
}

// ------------------------------------------------------------------ step 3: check

async function check(viewer, build_id) {
  const g = await gate(viewer, build_id);
  if (!g.ok) return g;
  const l = await latest(build_id);
  if (!l || !l.live_url) return { ok: false, kind: 'refused', says: 'There is no live address to check yet.' };
  const title = (String(g.build.html).match(/<title>([^<]*)<\/title>/i) || [])[1];
  const out = await stepRow(l.id, 'check', viewer, async () => {
    const r = await fetch(l.live_url, { signal: AbortSignal.timeout(15000) }).catch(() => null);
    if (!r) return { ok: false, says: 'I could not reach ' + l.live_url + ' yet. If it was just started, give it a few minutes.' };
    const text = await r.text().catch(() => '');
    if (!r.ok) return { ok: false, says: l.live_url + ' answered ' + r.status + ', so it is not serving the app yet.' };
    if (title && !text.includes(title)) return { ok: false, says: l.live_url + ' is up, but it is not showing the app I built, so I am not calling it live.' };
    return { ok: true, result: l.live_url, says: 'It is live. I opened ' + l.live_url + ' and it is serving the app.' };
  });
  return out.ok ? { ok: true, says: out.says } : { ok: false, kind: 'unavailable', says: out.says };
}

module.exports = { status, pushCode, host, check, packageFiles, suggestName, hostingOn };
