-- 023: the structured opportunity brief.
--
-- From the founder: browsing the Dream Market should make plain, at a glance, why you'd run this —
-- the problem it solves, who you'd serve, what you could realistically make, and why it might be
-- you. Clay's take already covers the narrative; this distills the specifics into four short,
-- scannable lines, grounded in what the concept already carries (the take, the computed economics,
-- the customer research) — never invented figures. Stored as a small JSON object on the concept:
--   { problem, customer, earning, why_you }  (all short strings; any may be absent).
-- Generated by Clay on demand or when a concept is listed; nullable until generated.

ALTER TABLE concepts ADD COLUMN IF NOT EXISTS brief jsonb;
